# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
   config.vm.network "private_network", ip: "192.168.33.10"
   #config.vm.network "public_network"
   config.vm.provision "ansible" do |ansible|
   ansible.verbose = "v"
   ansible.playbook = "playbook.yml"
   end
end
